### ISSUE TITLE
URL del vídeo incorrecta

### ISSUE THREAD

**Issue by Miguel-Herrero** [fitomad/BiciMAD-Bike-Identifier#1]
Enhorabuena, muy buena la aplicación y el uso de Keras y el reconocimiento de caracteres. Me gustaría encontrar tiempo para trastear también con estos temas.

He buscado el vídeo en Youtube y ya lo he visto, pero la URL que enlazas en el README creo que está mal porque enlaza al “editar” en Youtube, no la URL pública.

Creo que la correcta sería: https://www.youtube.com/watch?v=DwYoWG4OEZc

Saludos y muy buen trabajo!!! 👏 🏅

**Comment by fitomad** [comment]
El enlace abre el vídeo de demostración fuera del modo edición 👍 

¡Gracias por tus comentarios!
